name: Feature Request
description: Suggest a new feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: Describe the problem you're trying to solve or what motivates this feature request
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false
