"""Generates src/ids/idsSchema.generated.ts: the entity/attribute table the IDS
audit layer validates documents against. Source of truth is IfcOpenShell's
EXPRESS schemas (union of IFC2X3, IFC4, IFC4X3_ADD2), matching the official
IDS Audit tool's behaviour.

Run: <venv-python> scripts/generateIdsSchema.py
"""
import json
from pathlib import Path

import ifcopenshell.ifcopenshell_wrapper as w

KINDS = {"string": "s", "real": "d", "number": "d", "integer": "i", "boolean": "b", "logical": "l", "binary": "y"}


def attr_kind(attr):
    t = attr.type_of_attribute()
    if isinstance(t, w.aggregation_type):
        return "L"
    while isinstance(t, w.named_type):
        decl = t.declared_type()
        if isinstance(decl, w.type_declaration):
            inner = decl.declared_type()
            if isinstance(inner, w.aggregation_type):
                return "L"
            if isinstance(inner, w.simple_type):
                return KINDS.get(str(inner).strip("<>"), "s")
            t = inner
            continue
        if isinstance(decl, w.enumeration_type):
            return "e"
        if isinstance(decl, w.select_type):
            return "S"
        if isinstance(decl, w.entity):
            return "r"
        break
    if isinstance(t, w.simple_type):
        return KINDS.get(str(t).strip("<>"), "s")
    return "r"


entities: dict[str, dict[str, str]] = {}
masks: dict[str, dict[str, int]] = {}
for bit, name in ((1, "IFC2X3"), (2, "IFC4"), (4, "IFC4X3_ADD2")):
    try:
        schema = w.schema_by_name(name)
    except Exception:
        schema = w.schema_by_name(name.replace("_ADD2", ""))
    for decl in schema.declarations():
        if not isinstance(decl, w.entity):
            continue
        key = decl.name().upper()
        table = entities.setdefault(key, {})
        mask = masks.setdefault(key, {})
        if decl.is_abstract():
            table.setdefault("__abstract", "1")
        mask["__entity"] = mask.get("__entity", 0) | bit
        for attr in decl.all_attributes():
            table[attr.name()] = attr_kind(attr)
            mask[attr.name()] = mask.get(attr.name(), 0) | bit

# fold masks into the kind strings: "<kind><mask>" (mask omitted when 7 = all)
for key, table in entities.items():
    mask = masks[key]
    for attr, kind in list(table.items()):
        if attr == "__abstract":
            continue
        m = mask.get(attr, 7)
        table[attr] = kind if m == 7 else f"{kind}{m}"
    em = mask.get("__entity", 7)
    if em != 7:
        table["__schemas"] = str(em)

out = Path(__file__).resolve().parent.parent / "src" / "ids" / "idsSchema.generated.ts"
payload = json.dumps(entities, separators=(",", ":"), sort_keys=True)
out.write_text(
    "// AUTO-GENERATED by scripts/generateIdsSchema.py from IfcOpenShell's\n"
    "// EXPRESS schemas (IFC2X3 + IFC4 + IFC4X3 union). Do not edit manually.\n"
    "// Attribute kinds: s=string d=real i=integer b=boolean l=logical y=binary\n"
    "// e=enum S=select r=entity-ref L=list; a digit suffix is a schema bitmask\n"
    "// (1=IFC2X3 2=IFC4 4=IFC4X3, omitted when in all three); __abstract marks\n"
    "// abstract entities, __schemas the entity's own bitmask.\n"
    "export const IFC_ENTITY_ATTRIBUTES: Readonly<\n"
    "  Record<string, Readonly<Record<string, string>>>\n"
    f"> = {payload};\n"
)
print(f"wrote {out} ({out.stat().st_size} bytes, {len(entities)} entities)")
