"""Generates src/validation/qtoDefinitions.generated.ts from the official
buildingSMART gherkin-rules qto table (features/resources/IFC4/
qto_definitions.csv in buildingSMART/ifc-gherkin-rules), the source the
Validation Service's QTY001 rule checks against.

Run: python3 scripts/generateQtoDefinitions.py /path/to/qto_definitions.csv
"""
import ast
import csv
import json
import sys
from pathlib import Path

rows = {}
with open(sys.argv[1]) as f:
    for row in csv.DictReader(f):
        props = ast.literal_eval(row["property_definitions"])
        entities = ast.literal_eval(row["applicable_entities"])
        rows[row["Name"]] = {
            "entities": [e.upper() for e in entities],
            "quantities": {p["property_name"]: p["property_type"].upper() for p in props},
        }

out = Path(__file__).resolve().parent.parent / "src" / "validation" / "qtoDefinitions.generated.ts"
payload = json.dumps(rows, separators=(",", ":"), sort_keys=True)
out.write_text(
    "// AUTO-GENERATED by scripts/generateQtoDefinitions.py from the official\n"
    "// buildingSMART ifc-gherkin-rules qto_definitions.csv (IFC4). Do not edit.\n"
    "export interface QtoDefinition {\n"
    "  readonly entities: readonly string[];\n"
    "  readonly quantities: Readonly<Record<string, string>>;\n"
    "}\n"
    f"export const QTO_DEFINITIONS: Readonly<Record<string, QtoDefinition>> = {payload};\n"
)
print(f"wrote {out} ({out.stat().st_size} bytes, {len(rows)} sets)")
